baseurl:    /gophp7-ext

navigation:
    - text: Home
      url: /
    - text: Todo
      url: /todo.html
    - text: Catalog
      url: /extensions-catalog.html
    - text: Blog
      url: /blog.html
    - text: Testing extensions
      url: /testing-extensions.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
